============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
Already up to date.
[INFO] Loading configuration...
[INFO] ✅ Configuration loaded.
[INFO] Loading paths...
[INFO] ✅ Paths loaded.
[INFO] Creating paths if they don't exist...
[INFO] ✅ Paths created.
[INFO] Initializing preprocessing pipeline...
[INFO] Running preprocessing pipeline...
[INFO] ✅ Preprocessing pipeline complete.
[INFO] Running DreamGaussian pipeline...
[ERROR] ❌ Subprocess error with non-zero exit status 1
[ERROR] Standard error of the subprocess: Traceback (most recent call last):
  File "repos/dreamgaussian/main.py", line 565, in <module>
    opt = OmegaConf.merge(OmegaConf.load(args.config), OmegaConf.from_cli(extras))
  File "/home/jhuizing/.conda/envs/dreamgaussianV2/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home6/jhuizing/master-thesis-ds/configs/image.yaml'

Traceback (most recent call last):
  File "pipeline.py", line 82, in <module>
    raise cpe
  File "pipeline.py", line 68, in <module>
    result = subprocess.run(command, check=True, text=True, capture_output=True)
  File "/home/jhuizing/.conda/envs/dreamgaussianV2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'repos/dreamgaussian/main.py', '--config', 'configs/image.yaml', 'input=results/preprocessing/blueberry_rgba.png', 'save_path=name']' returned non-zero exit status 1.
